const ALERT_STATUS = {
  OPEN: "OPEN",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  INVESTIGATING: "INVESTIGATING",
  CLOSED: "CLOSED",
  DISMISSED: "DISMISSED",
};

const RULE_TYPES = {
  AMOUNT_THRESHOLD: "AMOUNT_THRESHOLD",
  VELOCITY: "VELOCITY",
  NEW_PAYEE: "NEW_PAYEE",
  DAILY_LIMIT: "DAILY_LIMIT",
};

const SEVERITY = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
};

const ALLOWED_TRANSITIONS = {
  [ALERT_STATUS.OPEN]: [ALERT_STATUS.ACKNOWLEDGED, ALERT_STATUS.DISMISSED],
  [ALERT_STATUS.ACKNOWLEDGED]: [ALERT_STATUS.INVESTIGATING, ALERT_STATUS.DISMISSED],
  [ALERT_STATUS.INVESTIGATING]: [ALERT_STATUS.CLOSED, ALERT_STATUS.DISMISSED],
  [ALERT_STATUS.CLOSED]: [],
  [ALERT_STATUS.DISMISSED]: [],
};

module.exports = {
  ALERT_STATUS,
  RULE_TYPES,
  SEVERITY,
  ALLOWED_TRANSITIONS,
};
